
title: GiantBoar
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  a website of sorts

# domain information
baseurl: "" # the subpath of your site, e.g. /blog
domain: giantboar.com
url: https://giantboar.custom
repository: GiantBoar/giantboar.github.io

# social links (comment out any unecessary ones)
socials:
  github: https://github.com/giantboar
  linkedin: https://www.linkedin.com/in/giantboar/
  #- twitter: 

# compilation variables
paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate

defaults:
  - scope: # blog posts
      path: ""
      type: "posts"
    values:
      layout: "post"
      published: true
      hidden: true
      pinned: false
      permalink: /blog/:year/:title

  - scope: # gamepages
      path: ""
      type: "games"
    values:
      layout: "gamepage"
      permalink: /games/:title

  - scope: # default 
      path: ""
    values:
      layout: "default"